---
 - name: 'Install Knock Server'
   hosts: all
   become: true
   gather_facts: true
   vars:

   tasks:
     - name: 'Install required packages'
       yum:
         name:
           - nano
           - net-tools
           - epel-release
           - telnet
         state: present

     - name: "Cpoy nux rpm"
       copy:
         src: ../templates/nux-dextop-release-0-5.el7.nux.noarch.rpm
         dest: /root/nux-dextop-release-0-5.el7.nux.noarch.rpm
       when: ansible_hostname=='inetRouter'

     - name: "Install nux rpm package"
       yum:
         name: /root/nux-dextop-release-0-5.el7.nux.noarch.rpm
         state: present
       when: ansible_hostname=='inetRouter'

     - name: 'Install knock-server'
       yum:
         name: knock-server
         state: present
       when: ansible_hostname=='inetRouter'

     - name: 'Create knock-port confgi'
       template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
       with_items:
         - { src: '../templates/knockd.conf.j2', dest: '/etc/knockd.conf', owner: 'root', group: 'root', mode: '0644'}
         - { src: '../templates/knockd.j2', dest: '/etc/sysconfig/knockd', owner: 'root', group: 'root', mode: '0644'}
       notify:
         - restart knockd
       when: ansible_hostname=='inetRouter'


     - name: 'Create knock-port confgi'
       template: src={{ item.src }} dest={{ item.dest }}
       with_items:
         - { src: '../templates/knock_openssh.sh', dest: '/root/knock_openssh.sh'}
         - { src: '../templates/knock_closessh.sh', dest: '/root/knock_closessh.sh'}
       when: ansible_hostname=='centralRouter'

   handlers:
     - name: restart knockd
       systemd:
         name: knockd
         state: restarted
         enabled: yes